/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 5.0 */
package parser;

public interface ParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTPROGRAM = 1;
  public int JJTSTATEMENTBLOCK = 2;
  public int JJTSTATEMENT = 3;
  public int JJTSEQUENTIALSTATEMENT = 4;
  public int JJTDECLARATIONSTATEMENT = 5;
  public int JJTASSIGNMENTSTATEMENT = 6;
  public int JJTCONDITIONALSATEMENT = 7;
  public int JJTLOOPSTATEMENT = 8;
  public int JJTCONDITIONAL = 9;
  public int JJTRELATION = 10;
  public int JJTEXPRESSION = 11;
  public int JJTADDITIVEEXPRESSION = 12;
  public int JJTMULTIPLICATIVEEXPRESSION = 13;
  public int JJTUNARYEXPRESSION = 14;
  public int JJTIDENTIFIER = 15;
  public int JJTINTEGER = 16;


  public String[] jjtNodeName = {
    "Start",
    "Program",
    "StatementBlock",
    "Statement",
    "SequentialStatement",
    "DeclarationStatement",
    "AssignmentStatement",
    "ConditionalSatement",
    "LoopStatement",
    "Conditional",
    "Relation",
    "Expression",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "UnaryExpression",
    "Identifier",
    "Integer",
  };
}
/* JavaCC - OriginalChecksum=71ac8cc82aac9cc7a0f8b33e7095e517 (do not edit this line) */
